[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  force = true

[[redirects]]
  from = "/l/*"
  to = "/.netlify/functions/l"
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200